In [41]:
import pandas as pd

In [42]:
dataset = pd.read_csv(r"C:\Users\Muhammad Zain Ul Aba\Desktop\machine-learning-step-16\boston_housing_practice_1000_rows.csv")
dataset.head(3)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,House_Price
0,1.40780,80.0,14.77,0,0.520,6.443,27.2,7.9972,1,682,12.9,379.75,11.99,30.1
1,9.03036,25.0,13.68,0,0.773,7.958,72.5,2.8120,16,424,19.0,334.43,30.29,22.3
2,3.95024,60.0,1.21,0,0.869,4.912,4.8,5.7281,5,657,12.5,392.55,4.68,24.6

In [43]:
dataset.shape

(1000, 14)

In [44]:
input_data = dataset.iloc[:,: -1]
input_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,1.40780,80.0,14.77,0,0.520,6.443,27.2,7.9972,1,682,12.9,379.75,11.99
1,9.03036,25.0,13.68,0,0.773,7.958,72.5,2.8120,16,424,19.0,334.43,30.29
2,3.95024,60.0,1.21,0,0.869,4.912,4.8,5.7281,5,657,12.5,392.55,4.68
3,2.73883,95.0,9.88,1,0.395,6.177,38.8,4.1598,3,488,12.6,260.86,31.44
4,0.50887,95.0,10.96,0,0.820,6.648,63.4,9.1047,23,410,15.1,294.29,25.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.28815,0.0,14.04,0,0.679,6.160,24.8,5.1583,8,649,16.0,377.14,8.02
996,7.47810,18.0,16.38,0,0.619,6.487,88.4,2.1324,23,529,20.2,344.43,7.91
997,0.44139,40.0,24.30,0,0.445,6.038,34.2,8.9093,13,305,17.7,323.31,22.33
998,9.00147,12.5,27.47,0,0.508,7.175,13.1,6.5428,8,488,12.4,383.49,26.36
999,1.77180,95.0,11.71,0,0.585,6.788,87.3,8.7964,17,409,13.8,376.80,5.45

In [45]:
output_data = dataset["House_Price"]
output_data

0      30.1
1      22.3
2      24.6
3      14.1
4      19.9
       ...
995    37.3
996    36.0
997    24.2
998    19.6
999    31.2
Name: House_Price, Length: 1000, dtype: float64

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data,test_size=0.25)

In [48]:
x_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
21,0.45070,18.0,26.20,0,0.610,6.336,91.7,4.4860,7,700,21.2,383.42,13.21
763,4.08710,0.0,12.69,0,0.570,6.904,26.5,8.7142,9,694,16.8,300.81,23.75
380,0.37725,60.0,19.44,0,0.626,6.821,6.9,11.5860,2,468,12.8,326.36,16.65
736,1.49494,80.0,25.04,0,0.408,7.256,85.7,7.6736,7,581,20.9,272.10,6.78
246,1.67681,0.0,1.03,0,0.705,5.505,55.5,4.9205,23,199,15.7,277.12,3.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,3.84313,80.0,14.42,0,0.546,5.919,45.3,8.7433,23,556,13.0,330.32,24.65
706,1.16739,40.0,8.20,0,0.667,6.136,53.8,10.5871,7,353,18.7,372.36,13.78
180,1.25140,25.0,10.02,0,0.748,4.787,79.4,5.9145,23,410,18.6,322.28,20.55
535,8.68852,80.0,10.11,0,0.864,6.256,38.0,4.2733,9,558,12.9,392.38,14.69
394,1.25020,40.0,15.76,0,0.738,6.576,41.9,10.4572,18,224,15.1,339.28,34.15

In [49]:
x_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
606,0.69328,95.0,24.07,0,0.853,5.745,96.9,7.4769,17,710,16.2,328.27,8.60
430,0.46292,25.0,16.45,0,0.840,8.406,92.2,6.7024,21,225,22.0,255.76,4.62
988,0.84869,18.0,16.69,0,0.762,5.472,29.5,7.7523,24,695,16.2,290.38,1.14
870,1.40191,95.0,18.44,0,0.479,7.079,50.5,5.8213,3,412,17.8,260.37,24.92
853,6.84994,60.0,24.53,0,0.849,6.793,18.8,8.1567,16,685,19.1,300.72,17.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,2.83809,80.0,27.13,0,0.616,6.063,87.7,10.7872,11,414,17.1,367.48,33.52
397,1.68107,18.0,5.67,0,0.788,5.305,15.9,3.6594,6,660,14.6,274.90,6.93
382,2.97420,12.5,18.00,0,0.849,6.242,20.4,3.9738,20,186,17.8,306.53,25.80
282,1.41281,95.0,13.19,1,0.385,5.521,85.1,6.3949,24,296,18.6,269.24,11.57
897,6.79980,18.0,1.20,0,0.418,7.248,14.8,4.7657,24,280,12.5,391.75,13.13

In [50]:
y_train

606    33.0
430    43.1
988    27.1
870    25.3
853    26.9
       ...
327    12.5
397    28.8
382    17.9
282    26.3
897    37.5
Name: House_Price, Length: 750, dtype: float64

In [51]:
y_train

606    33.0
430    43.1
988    27.1
870    25.3
853    26.9
       ...
327    12.5
397    28.8
382    17.9
282    26.3
897    37.5
Name: House_Price, Length: 750, dtype: float64

In [52]:
y_test

21     26.6
763    26.6
380    26.9
736    34.2
246    25.7
       ...
777    16.1
706    30.8
180    21.7
535    30.9
394    18.0
Name: House_Price, Length: 250, dtype: float64

In [53]:
x_train.shape, y_train.shape

((750, 13), (750,))

In [55]:
x_test.shape, y_test.shape

((250, 13), (250,))